# _config.yml

title: Axaxaxas mlö
author: Jorge Agramont
description: Archivo de ideas, reflexiones y cuentos. Dejemos que hablen los fantasmas / Archive of ideas, reflections, and tales. Let the ghosts speak.
theme: minimal  # Replace with other from jekyllthemes.org
